#!/usr/bin/python3

"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten 
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
difference is pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

import cProfile

def pentagonalGen(max):
    result = [ ]
   
    for i in range(1, max+1):
        result.append(i*(3*i-1)//2)
      
    return result
   
def main():
    num = 10000
    pentalist = pentagonalGen(num)
    pentaset = set(pentalist)
    lowestD = 10000000
    
    for i in range(num):
        x = pentalist[i]
        for j in range(i+1, num):
            y = pentalist[j]
            if y-x > lowestD: break
            if (y-x) in pentaset and (x+y) in pentaset:
                if y-x < lowestD:
                    lowestD = y-x
                    print(y, x)
            
    print(lowestD)
            
if __name__ == '__main__':
    cProfile.run('main()')