#!/usr/bin/python3

"""
Triangle, pentagonal, and hexagonal numbers are generated by the following 
formulae:
Triangle           Tn=n(n+1)/2           1, 3, 6, 10, 15, ...
Pentagonal           Pn=n(3n−1)/2           1, 5, 12, 22, 35, ...
Hexagonal           Hn=n(2n−1)           1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

import cProfile


def generatepent(n):
    result = [ ]
    for x in range(1, n):
        result.append(x*(3*x-1)/2)
    return result

def generatehex(n):
    result = [ ]
    for x in range(1, n):
        result.append(x*(2*x-1))
    return result

def intersect(a, b):
    return list(set(a) & set(b))

# All hexagonal numbers are also hexagonal numbers
def main():
    pent = generatepent(50000)
    hexa = generatehex(50000)

    print(intersect(pent, hexa))
   
if __name__ == '__main__':
    cProfile.run('main()')